import mongoose from "mongoose";
import dotenv from "dotenv";
import Activity from "./models/Activity.js";

dotenv.config();

const dummyEvents = [
  // Comedy Shows (6 events)
  {
    title: "LOL Bangalore Nights",
    image: "https://source.unsplash.com/800x600/?comedy,standup",
    description:
      "An unforgettable night of stand-up comedy with top performers.",
    location: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "Comedy Shows",
    language: "English",
    date: new Date("2025-07-15"),
    time: "19:00",
    duration: "2h",
    artists: ["Rahul Subramanian", "Kaneez Surka"],
    ticketPrice: 499,
    totalSeats: 200,
    availableSeats: 150,
    bookingCount: 50,
    ageLimit: 16,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Hyderabad HaHa Fest",
    image: "https://source.unsplash.com/800x600/?funny,stage",
    description:
      "Top comedians light up Hyderabad's stage with hilarious acts.",
    location: "Hyderabad",
    coordinates: { lat: 17.385, lng: 78.4867 },
    category: "Comedy Shows",
    language: "Hindi",
    date: new Date("2025-07-18"),
    time: "20:00",
    duration: "2h",
    artists: ["Sumukhi Suresh", "Aakash Gupta"],
    ticketPrice: 399,
    totalSeats: 250,
    availableSeats: 250,
    bookingCount: 0,
    ageLimit: 16,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Comedy at Cubbon Park",
    image: "https://source.unsplash.com/800x600/?outdoor,comedy",
    description: "Open-air comedy show under the stars in Bangalore.",
    location: "Bangalore",
    coordinates: { lat: 12.9768, lng: 77.5951 },
    category: "Comedy Shows",
    language: "English",
    date: new Date("2025-07-20"),
    time: "18:30",
    duration: "2h",
    artists: ["Kenny Sebastian", "Kanan Gill"],
    ticketPrice: 599,
    totalSeats: 300,
    availableSeats: 120,
    bookingCount: 180,
    ageLimit: 18,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Telugu Comedy Night",
    image: "https://source.unsplash.com/800x600/?telugu,comedy",
    description: "Laugh out loud with Hyderabad's best Telugu comedians.",
    location: "Hyderabad",
    coordinates: { lat: 17.4065, lng: 78.4772 },
    category: "Comedy Shows",
    language: "Telugu",
    date: new Date("2025-07-25"),
    time: "19:30",
    duration: "2.5h",
    artists: ["Srinivas Reddy", "Priyadarshi"],
    ticketPrice: 349,
    totalSeats: 180,
    availableSeats: 180,
    bookingCount: 0,
    ageLimit: 15,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Corporate Comedy Special",
    image: "https://source.unsplash.com/800x600/?office,comedy",
    description: "Humor that hits close to home for working professionals.",
    location: "Bangalore",
    coordinates: { lat: 12.9299, lng: 77.6279 },
    category: "Comedy Shows",
    language: "English",
    date: new Date("2025-07-30"),
    time: "20:00",
    duration: "2h",
    artists: ["Abish Mathew", "Azeem Banatwalla"],
    ticketPrice: 699,
    totalSeats: 150,
    availableSeats: 50,
    bookingCount: 100,
    ageLimit: 18,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Stand-up Open Mic",
    image: "https://source.unsplash.com/800x600/?mic,comedy",
    description: "Discover new comedy talent at this open mic night.",
    location: "Hyderabad",
    coordinates: { lat: 17.4254, lng: 78.5071 },
    category: "Comedy Shows",
    language: "Hindi/English",
    date: new Date("2025-08-02"),
    time: "19:00",
    duration: "3h",
    artists: ["Upcoming Talents"],
    ticketPrice: 199,
    totalSeats: 100,
    availableSeats: 100,
    bookingCount: 0,
    ageLimit: 16,
    isFeatured: false,
    status: "upcoming",
  },

  // Amusement Park (6 events)
  {
    title: "WonderLand Weekend",
    image: "https://source.unsplash.com/800x600/?amusement,park",
    description: "Enjoy thrilling rides and water fun for the whole family.",
    location: "Bangalore",
    coordinates: { lat: 12.9558, lng: 77.7012 },
    category: "Amusement Park",
    language: "English",
    date: new Date("2025-08-04"),
    time: "10:00",
    duration: "8h",
    artists: [],
    ticketPrice: 999,
    totalSeats: 500,
    availableSeats: 200,
    bookingCount: 300,
    ageLimit: 5,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "FunWorld Fiesta",
    image: "https://source.unsplash.com/800x600/?themepark,rides",
    description: "Family amusement day with unlimited fun and games.",
    location: "Hyderabad",
    coordinates: { lat: 17.4375, lng: 78.4483 },
    category: "Amusement Park",
    language: "Telugu",
    date: new Date("2025-08-04"),
    time: "09:30",
    duration: "9h",
    artists: [],
    ticketPrice: 849,
    totalSeats: 600,
    availableSeats: 400,
    bookingCount: 200,
    ageLimit: 5,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Water Splash Carnival",
    image: "https://source.unsplash.com/800x600/?waterpark,summer",
    description: "Beat the heat with exciting water rides and slides.",
    location: "Bangalore",
    coordinates: { lat: 12.9342, lng: 77.6228 },
    category: "Amusement Park",
    language: "English",
    date: new Date("2025-08-06"),
    time: "09:00",
    duration: "7h",
    artists: [],
    ticketPrice: 799,
    totalSeats: 400,
    availableSeats: 150,
    bookingCount: 250,
    ageLimit: 5,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Adventure Island",
    image: "https://source.unsplash.com/800x600/?adventure,park",
    description: "Thrilling rides and attractions for adventure seekers.",
    location: "Hyderabad",
    coordinates: { lat: 17.4289, lng: 78.4617 },
    category: "Amusement Park",
    language: "Telugu/English",
    date: new Date("2025-08-17"),
    time: "10:30",
    duration: "8h",
    artists: [],
    ticketPrice: 899,
    totalSeats: 350,
    availableSeats: 350,
    bookingCount: 0,
    ageLimit: 8,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Kids Fantasy Land",
    image: "https://source.unsplash.com/800x600/?kids,park",
    description: "Special amusement area designed for young children.",
    location: "Bangalore",
    coordinates: { lat: 12.9667, lng: 77.5667 },
    category: "Amusement Park",
    language: "English",
    date: new Date("2025-08-22"),
    time: "10:00",
    duration: "6h",
    artists: [],
    ticketPrice: 599,
    totalSeats: 200,
    availableSeats: 200,
    bookingCount: 0,
    ageLimit: 3,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Night Amusement Special",
    image: "https://source.unsplash.com/800x600/?night,park",
    description: "Experience the park in a whole new light after dark.",
    location: "Hyderabad",
    coordinates: { lat: 17.4415, lng: 78.4982 },
    category: "Amusement Park",
    language: "Telugu",
    date: new Date("2025-08-27"),
    time: "17:00",
    duration: "5h",
    artists: [],
    ticketPrice: 699,
    totalSeats: 300,
    availableSeats: 100,
    bookingCount: 200,
    ageLimit: 8,
    isFeatured: true,
    status: "upcoming",
  },

  // Theater Shows (6 events)
  {
    title: "Shakespeare Reimagined",
    image: "https://source.unsplash.com/800x600/?theater,drama",
    description: "Modern take on the classic play with contemporary themes.",
    location: "Bangalore",
    coordinates: { lat: 12.9865, lng: 77.6037 },
    category: "Theater Shows",
    language: "English",
    date: new Date("2025-08-03"),
    time: "18:00",
    duration: "2.5h",
    artists: ["StageCraft Ensemble"],
    ticketPrice: 599,
    totalSeats: 150,
    availableSeats: 50,
    bookingCount: 100,
    ageLimit: 14,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Drama-e-Dil",
    image: "https://source.unsplash.com/800x600/?stageplay,actors",
    description: "A romantic drama that will touch your heart.",
    location: "Hyderabad",
    coordinates: { lat: 17.3841, lng: 78.4569 },
    category: "Theater Shows",
    language: "Hindi",
    date: new Date("2025-08-08"),
    time: "19:00",
    duration: "3h",
    artists: ["Local Drama Co."],
    ticketPrice: 499,
    totalSeats: 180,
    availableSeats: 180,
    bookingCount: 0,
    ageLimit: 16,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Bangalore Broadway",
    image: "https://source.unsplash.com/800x600/?musical,theater",
    description: "Musical theater production with local talents.",
    location: "Bangalore",
    coordinates: { lat: 12.9784, lng: 77.6408 },
    category: "Theater Shows",
    language: "English",
    date: new Date("2025-08-13"),
    time: "19:30",
    duration: "2h",
    artists: ["Bangalore Theater Group"],
    ticketPrice: 699,
    totalSeats: 200,
    availableSeats: 80,
    bookingCount: 120,
    ageLimit: 12,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Telugu Natakam",
    image: "https://source.unsplash.com/800x600/?telugu,theater",
    description: "Classic Telugu play performed by veteran artists.",
    location: "Hyderabad",
    coordinates: { lat: 17.4156, lng: 78.4347 },
    category: "Theater Shows",
    language: "Telugu",
    date: new Date("2025-08-18"),
    time: "18:30",
    duration: "2.5h",
    artists: ["Telugu Nataka Academy"],
    ticketPrice: 399,
    totalSeats: 220,
    availableSeats: 220,
    bookingCount: 0,
    ageLimit: 15,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Improv Night",
    image: "https://source.unsplash.com/800x600/?improv,comedy",
    description: "Interactive improv theater where audience participates.",
    location: "Bangalore",
    coordinates: { lat: 12.9352, lng: 77.6245 },
    category: "Theater Shows",
    language: "English",
    date: new Date("2025-08-23"),
    time: "20:00",
    duration: "2h",
    artists: ["Bangalore Improv Collective"],
    ticketPrice: 349,
    totalSeats: 120,
    availableSeats: 40,
    bookingCount: 80,
    ageLimit: 16,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Hyderabad Drama Festival",
    image: "https://source.unsplash.com/800x600/?festival,theater",
    description: "Week-long drama festival featuring multiple plays.",
    location: "Hyderabad",
    coordinates: { lat: 17.4239, lng: 78.4738 },
    category: "Theater Shows",
    language: "Hindi/Telugu",
    date: new Date("2025-08-28"),
    time: "18:00",
    duration: "3h",
    artists: ["Multiple Theater Groups"],
    ticketPrice: 449,
    totalSeats: 250,
    availableSeats: 250,
    bookingCount: 0,
    ageLimit: 18,
    isFeatured: false,
    status: "upcoming",
  },

  // Adventures and Fun (7 events)
  {
    title: "Go Kart Racing Bangalore",
    image: "https://source.unsplash.com/800x600/?gokart,adventure",
    description: "High-speed racing experience for karting enthusiasts.",
    location: "Bangalore",
    coordinates: { lat: 12.9222, lng: 77.6188 },
    category: "Adventures And Fun",
    language: "English",
    date: new Date("2025-08-04"),
    time: "11:00",
    duration: "4h",
    artists: [],
    ticketPrice: 799,
    totalSeats: 50,
    availableSeats: 20,
    bookingCount: 30,
    ageLimit: 16,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Zipline & Rope Course",
    image: "https://source.unsplash.com/800x600/?zipline,forest",
    description: "Challenge yourself with high rope activities and ziplining.",
    location: "Hyderabad",
    coordinates: { lat: 17.4, lng: 78.462 },
    category: "Adventures And Fun",
    language: "English",
    date: new Date("2025-08-09"),
    time: "09:00",
    duration: "5h",
    artists: [],
    ticketPrice: 899,
    totalSeats: 40,
    availableSeats: 40,
    bookingCount: 0,
    ageLimit: 14,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Paintball Battle",
    image: "https://source.unsplash.com/800x600/?paintball,game",
    description: "Team-based paintball competition with strategy and fun.",
    location: "Bangalore",
    coordinates: { lat: 12.9123, lng: 77.6445 },
    category: "Adventures And Fun",
    language: "English",
    date: new Date("2025-08-14"),
    time: "10:30",
    duration: "3h",
    artists: [],
    ticketPrice: 599,
    totalSeats: 60,
    availableSeats: 60,
    bookingCount: 0,
    ageLimit: 15,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Trekking Expedition",
    image: "https://source.unsplash.com/800x600/?trekking,mountain",
    description: "Guided trek through scenic trails near Hyderabad.",
    location: "Hyderabad",
    coordinates: { lat: 17.45, lng: 78.5 },
    category: "Adventures And Fun",
    language: "English/Telugu",
    date: new Date("2025-08-19"),
    time: "06:00",
    duration: "6h",
    artists: [],
    ticketPrice: 499,
    totalSeats: 30,
    availableSeats: 10,
    bookingCount: 20,
    ageLimit: 18,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Scuba Diving Experience",
    image: "https://source.unsplash.com/800x600/?scuba,diving",
    description: "Beginner-friendly scuba diving in controlled environment.",
    location: "Bangalore",
    coordinates: { lat: 12.9423, lng: 77.5809 },
    category: "Adventures And Fun",
    language: "English",
    date: new Date("2025-08-24"),
    time: "09:30",
    duration: "4h",
    artists: [],
    ticketPrice: 1299,
    totalSeats: 20,
    availableSeats: 5,
    bookingCount: 15,
    ageLimit: 16,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Rock Climbing Challenge",
    image: "https://source.unsplash.com/800x600/?rock,climbing",
    description: "Indoor rock climbing with different difficulty levels.",
    location: "Hyderabad",
    coordinates: { lat: 17.41, lng: 78.49 },
    category: "Adventures And Fun",
    language: "English",
    date: new Date("2025-08-29"),
    time: "14:00",
    duration: "3h",
    artists: [],
    ticketPrice: 699,
    totalSeats: 25,
    availableSeats: 25,
    bookingCount: 0,
    ageLimit: 14,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "ATV Off-Road Adventure",
    image: "https://source.unsplash.com/800x600/?atv,offroad",
    description: "All-terrain vehicle ride through challenging tracks.",
    location: "Bangalore",
    coordinates: { lat: 12.9012, lng: 77.5923 },
    category: "Adventures And Fun",
    language: "English",
    date: new Date("2025-08-30"),
    time: "10:00",
    duration: "2h",
    artists: [],
    ticketPrice: 899,
    totalSeats: 15,
    availableSeats: 15,
    bookingCount: 0,
    ageLimit: 18,
    isFeatured: true,
    status: "upcoming",
  },

  // Music Shows (6 events)
  {
    title: "Rock On Bangalore",
    image: "https://source.unsplash.com/800x600/?concert,rockband",
    description: "An electric night of rock and indie music performances.",
    location: "Bangalore",
    coordinates: { lat: 12.9456, lng: 77.6113 },
    category: "Music Shows",
    language: "English",
    date: new Date("2025-09-05"),
    time: "20:00",
    duration: "3h",
    artists: ["Avial", "Thermal & a Quarter", "Parvaaz"],
    ticketPrice: 999,
    totalSeats: 500,
    availableSeats: 100,
    bookingCount: 400,
    ageLimit: 18,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Hyderabad Beats",
    image: "https://source.unsplash.com/800x600/?music,festival",
    description: "Bollywood and folk fusion concert for all music lovers.",
    location: "Hyderabad",
    coordinates: { lat: 17.395, lng: 78.485 },
    category: "Music Shows",
    language: "Telugu/Hindi",
    date: new Date("2025-08-10"),
    time: "18:30",
    duration: "3h",
    artists: ["Mangli", "DJ Chetas", "Sid Sriram"],
    ticketPrice: 799,
    totalSeats: 600,
    availableSeats: 200,
    bookingCount: 400,
    ageLimit: 16,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Jazz Under the Stars",
    image: "https://source.unsplash.com/800x600/?jazz,night",
    description: "Smooth jazz performances in an open-air setting.",
    location: "Bangalore",
    coordinates: { lat: 12.9675, lng: 77.5998 },
    category: "Music Shows",
    language: "English",
    date: new Date("2025-08-15"),
    time: "19:00",
    duration: "2.5h",
    artists: ["Jazz Junction Band", "Neha Sargam"],
    ticketPrice: 699,
    totalSeats: 300,
    availableSeats: 300,
    bookingCount: 0,
    ageLimit: 18,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Ghazal Evening",
    image: "https://source.unsplash.com/800x600/?ghazal,singer",
    description: "Soulful ghazal performances by renowned artists.",
    location: "Hyderabad",
    coordinates: { lat: 17.4023, lng: 78.4709 },
    category: "Music Shows",
    language: "Urdu/Hindi",
    date: new Date("2025-08-20"),
    time: "19:30",
    duration: "2h",
    artists: ["Pankaj Udhas", "Talat Aziz"],
    ticketPrice: 899,
    totalSeats: 400,
    availableSeats: 150,
    bookingCount: 250,
    ageLimit: 15,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "EDM Night",
    image: "https://source.unsplash.com/800x600/?edm,dj",
    description: "High-energy electronic dance music festival.",
    location: "Bangalore",
    coordinates: { lat: 12.953, lng: 77.6273 },
    category: "Music Shows",
    language: "English",
    date: new Date("2025-08-25"),
    time: "21:00",
    duration: "4h",
    artists: ["Nucleya", "Ritviz", "DJ Snake"],
    ticketPrice: 1299,
    totalSeats: 800,
    availableSeats: 300,
    bookingCount: 500,
    ageLimit: 21,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Carnatic Classical Concert",
    image: "https://source.unsplash.com/800x600/?carnatic,music",
    description: "Traditional South Indian classical music performance.",
    location: "Hyderabad",
    coordinates: { lat: 17.415, lng: 78.4867 },
    category: "Music Shows",
    language: "Telugu/Sanskrit",
    date: new Date("2025-08-30"),
    time: "18:00",
    duration: "2.5h",
    artists: ["TM Krishna", "Sudha Raghunathan"],
    ticketPrice: 499,
    totalSeats: 350,
    availableSeats: 350,
    bookingCount: 0,
    ageLimit: 12,
    isFeatured: false,
    status: "upcoming",
  },

  // Art and Craft (6 events)
  {
    title: "Pottery & Paint",
    image: "https://source.unsplash.com/800x600/?art,craft",
    description: "Hands-on workshop for pottery making and painting.",
    location: "Bangalore",
    coordinates: { lat: 12.9581, lng: 77.601 },
    category: "Art And Craft",
    language: "English",
    date: new Date("2025-08-06"),
    time: "15:00",
    duration: "2h",
    artists: ["Studio Claytopia"],
    ticketPrice: 599,
    totalSeats: 20,
    availableSeats: 5,
    bookingCount: 15,
    ageLimit: 12,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Handmade Card Workshop",
    image: "https://source.unsplash.com/800x600/?crafting,artwork",
    description: "Learn to create beautiful handmade greeting cards.",
    location: "Hyderabad",
    coordinates: { lat: 17.3902, lng: 78.4721 },
    category: "Art And Craft",
    language: "English/Telugu",
    date: new Date("2025-08-11"),
    time: "14:00",
    duration: "2h",
    artists: ["Crafty Creators"],
    ticketPrice: 399,
    totalSeats: 25,
    availableSeats: 25,
    bookingCount: 0,
    ageLimit: 10,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Macrame Wall Hanging",
    image: "https://source.unsplash.com/800x600/?macrame,craft",
    description: "Learn the art of macrame to create beautiful wall decor.",
    location: "Bangalore",
    coordinates: { lat: 12.9358, lng: 77.6253 },
    category: "Art And Craft",
    language: "English",
    date: new Date("2025-08-16"),
    time: "11:00",
    duration: "3h",
    artists: ["Fiber Arts Studio"],
    ticketPrice: 699,
    totalSeats: 15,
    availableSeats: 15,
    bookingCount: 0,
    ageLimit: 14,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Warli Painting Class",
    image: "https://source.unsplash.com/800x600/?warli,art",
    description: "Traditional tribal art workshop for beginners.",
    location: "Hyderabad",
    coordinates: { lat: 17.4256, lng: 78.4743 },
    category: "Art And Craft",
    language: "Telugu/English",
    date: new Date("2025-08-21"),
    time: "16:00",
    duration: "2h",
    artists: ["Tribal Art Collective"],
    ticketPrice: 499,
    totalSeats: 20,
    availableSeats: 10,
    bookingCount: 10,
    ageLimit: 12,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Resin Art Workshop",
    image: "https://source.unsplash.com/800x600/?resin,art",
    description: "Create stunning resin art pieces with professional guidance.",
    location: "Bangalore",
    coordinates: { lat: 12.9428, lng: 77.6267 },
    category: "Art And Craft",
    language: "English",
    date: new Date("2025-08-26"),
    time: "13:00",
    duration: "3h",
    artists: ["Resin Art Studio"],
    ticketPrice: 899,
    totalSeats: 12,
    availableSeats: 12,
    bookingCount: 0,
    ageLimit: 16,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Origami Masterclass",
    image: "https://source.unsplash.com/800x600/?origami,paper",
    description: "Learn advanced origami techniques from a master.",
    location: "Hyderabad",
    coordinates: { lat: 17.4358, lng: 78.4987 },
    category: "Art And Craft",
    language: "English",
    date: new Date("2025-08-01"),
    time: "15:30",
    duration: "2h",
    artists: ["Origami Masters"],
    ticketPrice: 349,
    totalSeats: 18,
    availableSeats: 18,
    bookingCount: 0,
    ageLimit: 10,
    isFeatured: true,
    status: "upcoming",
  },

  // Upskills and Training (6 events)
  {
    title: "Frontend Dev Bootcamp",
    image: "https://source.unsplash.com/800x600/?coding,training",
    description: "Intensive workshop on modern frontend development.",
    location: "Bangalore",
    coordinates: { lat: 12.9741, lng: 77.5914 },
    category: "Upskills And Training",
    language: "English",
    date: new Date("2025-08-07"),
    time: "10:00",
    duration: "6h",
    artists: ["Neetu Sarkar"],
    ticketPrice: 1299,
    totalSeats: 30,
    availableSeats: 10,
    bookingCount: 20,
    ageLimit: 18,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "AI for Beginners",
    image: "https://source.unsplash.com/800x600/?ai,training",
    description: "Introduction to artificial intelligence concepts.",
    location: "Hyderabad",
    coordinates: { lat: 17.385, lng: 78.4867 },
    category: "Upskills And Training",
    language: "English",
    date: new Date("2025-08-12"),
    time: "10:00",
    duration: "5h",
    artists: ["TechMentor.ai"],
    ticketPrice: 999,
    totalSeats: 40,
    availableSeats: 40,
    bookingCount: 0,
    ageLimit: 16,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Digital Marketing Crash Course",
    image: "https://source.unsplash.com/800x600/?digital,marketing",
    description: "Learn essential digital marketing strategies.",
    location: "Bangalore",
    coordinates: { lat: 12.9685, lng: 77.6412 },
    category: "Upskills And Training",
    language: "English",
    date: new Date("2025-08-17"),
    time: "09:30",
    duration: "7h",
    artists: ["Digital Growth Academy"],
    ticketPrice: 1499,
    totalSeats: 25,
    availableSeats: 5,
    bookingCount: 20,
    ageLimit: 18,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Data Science Fundamentals",
    image: "https://source.unsplash.com/800x600/?data,science",
    description: "Hands-on introduction to data science tools.",
    location: "Hyderabad",
    coordinates: { lat: 17.4158, lng: 78.4345 },
    category: "Upskills And Training",
    language: "English",
    date: new Date("2025-08-22"),
    time: "11:00",
    duration: "6h",
    artists: ["Data Wizards"],
    ticketPrice: 1199,
    totalSeats: 35,
    availableSeats: 35,
    bookingCount: 0,
    ageLimit: 18,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Blockchain Workshop",
    image: "https://source.unsplash.com/800x600/?blockchain,technology",
    description: "Understand blockchain technology and applications.",
    location: "Bangalore",
    coordinates: { lat: 12.9356, lng: 77.6145 },
    category: "Upskills And Training",
    language: "English",
    date: new Date("2025-08-27"),
    time: "13:00",
    duration: "4h",
    artists: ["Blockchain Experts"],
    ticketPrice: 1599,
    totalSeats: 20,
    availableSeats: 20,
    bookingCount: 0,
    ageLimit: 18,
    isFeatured: true,
    status: "upcoming",
  },
  {
    title: "Cloud Computing Basics",
    image: "https://source.unsplash.com/800x600/?cloud,computing",
    description: "Introduction to cloud platforms and services.",
    location: "Hyderabad",
    coordinates: { lat: 17.4253, lng: 78.4578 },
    category: "Upskills And Training",
    language: "English",
    date: new Date("2025-08-02"),
    time: "10:00",
    duration: "5h",
    artists: ["Cloud Masters"],
    ticketPrice: 899,
    totalSeats: 30,
    availableSeats: 30,
    bookingCount: 0,
    ageLimit: 18,
    isFeatured: false,
    status: "upcoming",
  },

  // Workshops (7 events)
  {
    title: "Photography Basics",
    image: "https://source.unsplash.com/800x600/?camera,workshop",
    description: "Learn photography fundamentals from professionals.",
    location: "Bangalore",
    coordinates: { lat: 12.96, lng: 77.6387 },
    category: "Workshops",
    language: "English",
    date: new Date("2025-08-08"),
    time: "11:00",
    duration: "3h",
    artists: ["Lens Masters"],
    ticketPrice: 799,
    totalSeats: 15,
    availableSeats: 15,
    bookingCount: 0,
    ageLimit: 16,
    isFeatured: false,
    status: "upcoming",
  },
  {
    title: "Makeup Mastery Workshop",
    image: "https://source.unsplash.com/800x600/?makeup,beauty",
    description:
      "Professional makeup techniques for daily and special occasions.",
    location: "Hyderabad",
    coordinates: { lat: 17.3904, lng: 78.4853 },
    category: "Workshops",
    language: "English/Telugu",
    date: new Date("2025-09-13"),
    time: "14:00",
    duration: "3h",
    artists: ["GlamGurus"],
    ticketPrice: 999,
    totalSeats: 20,
    availableSeats: 5,
    bookingCount: 15,
    ageLimit: 16,
    isFeatured: true,
    status: "upcoming",
  },
];

(async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log("✅ Connected to MongoDB");

    // Optional: Clear old data
    await Activity.deleteMany({});
    console.log("🧹 Old data cleared");

    await Activity.insertMany(dummyEvents);
    console.log("🎉 Dummy events seeded successfully!");
  } catch (err) {
    console.error("❌ Seeding error:", err);
  } finally {
    mongoose.disconnect();
  }
})();
